### ISSUE TITLE
DBSCAN example datasets?

### ISSUE THREAD

**Issue by OberstWB** [mlpack/examples#150]
hi,how can i get the file 'contact-tracing.csv'，i can not download from the url"https://lab.mlpack.org/data/contact-tracing.csv"

**Comment by rcurtin** [comment]
@zoq should we add this CSV to mlpack.org/datasets/examples?  If so let me know... I don't have a copy of the file though (sorry @OberstWB)

**Comment by zoq** [comment]
Yes, I'm currently updating the binder jupyter instance, one step is to consolidated all the datasets into one place.

**Comment by rcurtin** [comment]
Hey @OberstWB, we got the website updated with new locations for the datasets.  The contact tracing dataset can be downloaded here:

http://mlpack.org/datasets/notebooks/contact-tracing.csv

I think in the upcoming days we might update the URLs to use mlpack.org instead of lab.mlpack.org, but in any case, all the notebook datasets are available in that directory: http://mlpack.org/datasets/notebooks/ :+1:
