### ISSUE TITLE
Only fit `MinMaxScaler` on training data in LSTM examples

### ISSUE THREAD

**Issue by rcurtin** [mlpack/examples#43]
This comes from https://github.com/mlpack/models/pull/36#discussion_r371056033.

Right now, the LSTM examples use `MinMaxScaler` to scale the data.  But they use all of the data to fit the `MinMaxScaler`, which is actually a leakage of test data into the training process, and is not good data science practice. :)

So, it should be a simple change to ensure that `MinMaxScaler`'s `Fit()` method is only called with the training data.

**Comment by zsogitbe** [comment]
Be careful here because if you only calculate the min, max and scale (fit) for the training part of the data then the test data may be out of range and this may influence the test results significantly in a wrong way. Furthermore, the final results will also be wrong because the test data which is used for the prediction is wrongly inverse transformed! 
If you would want to separate the normalization of the two data sets then the only solution is using two MinMaxScalers, one for the training data and one for the test data and this will complicate the code significantly and will not be useful for the comprehension. I have also doubt about the usefulness of this separation and this will only make a difference if the training and test data sets are significantly different.
For the above reasons I would not recommend this change for this example. Perhaps you could add a comment with your name to that part of the code with some explanation if you think that something may be done differently.

**Comment by rcurtin** [comment]
This is standard data science practice and if I saw someone in my company doing their preprocessing on the entire dataset, I would make them change it. :)  The train/test split process for any machine learning algorithm is built on the assumption that the data distribution that the training points and test points arise from is the same.  If this is not true, the model will have serious issues when it's used in production.

So, you're right, in practice, *if* the distribution of training points and test points are the same, it doesn't make too much difference.  But if those distributions are *not* the same (and this can often happen in practice), then it *does* make a difference and can lead to really incorrect beliefs about how the system will perform in practice.

**Comment by zsogitbe** [comment]
Yes you are right, the generalization error (the reason why we split in training and testing sets) is only valid if both training and testing sets are coming from the same distribution (otherwise our statistical rules do not apply anymore). If they are not coming from the same distribution then the generalization error is not representative, therefore does not have any sense to test the model with the testing data (I am exaggerating a bit)! So, you are right but in the case in which you find your proposal important the error will not be representative anyway. It is a rather theoretical discussion and I think that in practice it does not really matter because in either way the generalization error will be wrong if the training and testing data are not coming from the same distribution! Furthermore, it will not make a huge difference on the results if you do so.

**Comment by rcurtin** [comment]
> It is a rather theoretical discussion and I think that in practice it does not really matter

Yes, it is a discussion about statistics theory, but it *does* matter because it is an example we are showing to people who are interested in using mlpack for their applications.  Therefore, we should try to avoid doing things that are inadvisable (theoretically or otherwise) in that example, and hence, this issue is open.

**Comment by kartikdutt18** [comment]
Hi @rcurtin, There is already a PR open for this issue. If you get a chance, kindly take a look.
