### ISSUE TITLE
Additional Model Application Examples

### ISSUE THREAD

**Issue by saraansh1999** [mlpack/examples#59]
I wanted to ask if the GSOC idea of implementing the ANN applications is to be done in this repo?

**Comment by kartikdutt18** [comment]
Hi @saraansh1999, Yes. Its is done here. I think we can close this then what do you think?

**Comment by saraansh1999** [comment]
I had a few ideas for the project and the things that can be implemented:

CNNs:
1. Image Colorization
2. Style Transfer
3. Face Detector
4. Pose estimation
5. Visual Tracking
6. Facial Biometric Spoof Detector
7. Generation of Fake images

RNNs:
1. Potry generation
2. Language Translation

Others:
1. Visual Question Answering


Would love to hear your ideas/suggestions on this.

**Comment by kartikdutt18** [comment]
Hi @saraansh1999, This is a great list. However I think it might be a better idea to discuss this on a public channel so that more people can jump in to help you. I personally prefer the mailing list because you can write a bit more compared to the IRC.
This just a suggestion, you can keep this issue open if you like.
